spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:hsqldb:file:hsqldb
    username: sa
    password: sa
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  application:
    name: sign
task:
  sign:
    cron: 5 30 12 * * ?
server:
  port: 7000